name: Build

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:


jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: simplepools-website-frontend/package-lock.json
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: npm install simplepools-website-frontend
      working-directory: simplepools-website-frontend
      run: |
        npm install
        npm run build
    - name: Build with Maven in simplepools-webapp
      working-directory: simplepools-webapp
      run: mvn clean install spring-boot:repackage
