name: Build front-end and server

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:


jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js '16.x'
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: simplepools-website-frontend/package-lock.json
    - working-directory: simplepools-website-frontend
      run: npm install
    - working-directory: simplepools-website-frontend
      run: npm run build
  
  build-server:
    needs: build-frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Build with Maven
      working-directory: simplepools-webapp
      run: mvn clean install spring-boot:repackage
    - run: find simplepools-webapp/target
